sudo: required
language: generic 
service:
  - docker

before_install:
  - docker build -t cppragada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cppragada/react-test npm test

after_success
  - docker build -t cppragada/multi-client ./client
  - docker build -t cppragada/multi-nginx ./nginx
  - docker build -t cppragada/multi-server ./server
  - docker build -t cppragada/multi-worker ./worker

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push cppragada/multi-client
- docker push cppragada/multi-nginx
- docker push cppragada/multi-server
- docker push cppragada/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  #below bucketname should be get from the AWS created bucket
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
 